flood_control.settings:
  type: config_object
  label: 'Flood Control Settings'
  mapping:
    user_failed_login_ip_limit:
      type: integer
      label: 'A default User Failed Login IP limit'
    user_failed_login_ip_window:
      type: integer
      label: 'User Failed Login IP Window'
    user_failed_login_user_limit:
      type: integer
      label: 'User Failed Login User limit'
    user_failed_login_user_window:
      type: integer
      label: 'User Failed Login User Window'
    contact_threshold_limit:
      type: integer
      label: 'Contact threshold limit'
    contact_threshold_window:
      type: integer
      label: 'Contact threshold window'
